/**
 * Technical Keyword Patterns
 * 
 * Comprehensive list of technical keywords for matching resumes and job descriptions.
 * This is a static list that can be imported and used across the application.
 * 
 * Usage:
 *   const { TECHNICAL_PATTERNS } = require('./technicalPatterns');
 *   const keywords = extractKeywords(text, TECHNICAL_PATTERNS);
 */

const TECHNICAL_PATTERNS = [

    // ============================================
    // PROGRAMMING LANGUAGES
    // ============================================
    'Python', 'SQL', 'Java', 'JavaScript', 'TypeScript', 'Go', 'Golang', 'C', 'C\\+\\+', 'C#', 'Scala', 'R', 'Ruby', 'PHP', 'Swift', 'Kotlin', 'Rust', 'Bash', 'Shell', 'PowerShell', 'Perl', 'Lua', 'Haskell', 'Elixir', 'Erlang', 'Clojure', 'F#', 'MATLAB', 'Julia', 'Groovy', 'Dart', 'Objective-C', 'Assembly', 'COBOL', 'Fortran', 'Solidity', 'Zig', 'Nim', 'Crystal', 'OCaml',

    // ============================================
    // ML/AI FRAMEWORKS & LIBRARIES
    // ============================================
    'PyTorch', 'TensorFlow', 'Keras', 'Scikit-Learn', 'Scikit Learn', 'XGBoost', 'LightGBM', 'CatBoost', 'Hugging Face', 'Hugging Face Transformers', 'LangChain', 'LlamaIndex', 'JAX', 'MXNet', 'Caffe', 'ONNX', 'OpenCV', 'spaCy', 'NLTK', 'Gensim', 'FastAI', 'Stable Diffusion', 'Diffusers', 'AutoML', 'H2O.ai', 'Ray', 'Ray Tune', 'Optuna', 'Triton', 'TensorRT', 'DeepSpeed', 'Megatron', 'CrewAI', 'AutoGen', 'Semantic Kernel', 'OpenAI SDK', 'Anthropic SDK', 'Cohere', 'LiteLLM', 'Ollama', 'vLLM',

    // ============================================
    // DATA SCIENCE LIBRARIES
    // ============================================
    'NumPy', 'Pandas', 'SciPy', 'Matplotlib', 'Seaborn', 'Plotly', 'Bokeh', 'Dask', 'Polars', 'Statsmodels', 'SymPy', 'NetworkX', 'Arrow', 'PyArrow', 'Great Expectations',

    // ============================================
    // CLOUD PLATFORMS & SERVICES
    // ============================================
    'AWS', 'Amazon Web Services', 'Azure', 'Microsoft Azure', 'GCP', 'Google Cloud', 'Google Cloud Platform', 'S3', 'EC2', 'Lambda', 'SageMaker', 'Azure ML', 'Azure Data Factory', 'Azure OpenAI', 'Blob Storage', 'AKS', 'EKS', 'GKE', 'Cloud Computing', 'Cloud Computing Platforms', 'Vertex AI', 'Bedrock', 'DigitalOcean', 'Heroku', 'Linode', 'Cloudflare', 'Vercel', 'Netlify', 'Railway', 'Render', 'Fly.io', 'IBM Cloud', 'Oracle Cloud', 'Alibaba Cloud', 'CloudFront', 'Route 53', 'IAM', 'VPC', 'RDS', 'ECS', 'ECR', 'SNS', 'SQS', 'Kinesis', 'Glue', 'Athena', 'EMR',

    // ============================================
    // DATABASES
    // ============================================
    'PostgreSQL', 'MySQL', 'MongoDB', 'Redis', 'Cassandra', 'Elasticsearch', 'Snowflake', 'BigQuery', 'Redshift', 'DynamoDB', 'CosmosDB', 'SQL Server', 'Oracle', 'SQLite', 'Neo4j', 'VectorDBs', 'Vector Databases', 'Pinecone', 'Weaviate', 'Milvus', 'Chroma', 'Qdrant', 'FAISS', 'Graph Databases', 'Relational Databases', 'NoSQL', 'MariaDB', 'CockroachDB', 'TimescaleDB', 'InfluxDB', 'Prometheus', 'Clickhouse', 'Couchbase', 'HBase', 'Memcached', 'Supabase', 'PlanetScale', 'Neon', 'Firebase', 'Firestore', 'Airtable', 'RethinkDB', 'ArangoDB',

    // ============================================
    // AI/ML CONCEPTS
    // ============================================
    'Machine Learning', 'Deep Learning', 'Natural Language Processing', 'NLP', 'Computer Vision', 'Large Language Models', 'LLMs', 'GPT', 'BERT', 'GPT-Style Models', 'Transformers', 'Generative AI', 'GenAI', 'AI', 'Artificial Intelligence', 'Prompt Engineering', 'Retrieval-Augmented Generation', 'RAG', 'Fine-Tuning', 'Transfer Learning', 'Zero-Shot Learning', 'Few-Shot Learning', 'Embeddings', 'Semantic Search', 'Entity Extraction', 'Tokenization', 'Sentiment Analysis', 'Classification', 'Clustering', 'Regression', 'Time Series', 'Forecasting', 'Anomaly Detection', 'Recommendation Systems', 'Reinforcement Learning', 'Supervised Learning', 'Unsupervised Learning', 'Semi-Supervised Learning', 'Neural Networks', 'CNNs', 'RNNs', 'LSTMs', 'GANs', 'Autoencoders', 'Object Detection', 'Image Classification', 'Feature Extraction', 'Feature Engineering', 'Feature Selection', 'Hyperparameter Tuning', 'Model Training', 'Model Evaluation', 'Model Deployment', 'Model Monitoring', 'Model Versioning', 'Drift Detection', 'Data Drift', 'Model Drift', 'A/B Testing', 'Experimentation', 'Evaluation Metrics', 'Evaluation Metric Frameworks', 'Benchmarking', 'Ablation Studies', 'Agentic AI', 'AI Agents', 'Multi-Agent Systems', 'Chain-of-Thought', 'Instruction Tuning', 'RLHF', 'Reinforcement Learning from Human Feedback', 'DPO', 'LoRA', 'QLoRA', 'PEFT', 'Quantization', 'Model Compression', 'Knowledge Distillation', 'Explainability', 'Interpretability', 'XAI', 'Responsible AI', 'AI Safety', 'Bias Detection', 'Fairness', 'Multimodal AI', 'Vision-Language Models', 'Speech Recognition', 'Text-to-Speech', 'OCR', 'Document AI', 'Graph Neural Networks', 'GNNs', 'Attention Mechanisms', 'Self-Supervised Learning', 'Contrastive Learning', 'Foundation Models',

    // ============================================
    // MLOPS & DATA ENGINEERING
    // ============================================
    'MLOps', 'MLflow', 'Weights & Biases', 'Weights and Biases', 'DVC', 'Airflow', 'Apache Airflow', 'Kubeflow', 'Apache Spark', 'PySpark', 'Spark', 'Kafka', 'Apache Kafka', 'Flink', 'Hadoop', 'Hive', 'Presto', 'Databricks', 'ETL', 'ETL Pipelines', 'Data Pipelines', 'Data Engineering', 'Data Ingestion', 'Batch Processing', 'Stream Processing', 'Real-Time Processing', 'Distributed Processing', 'Distributed Training', 'Multi-GPU Training', 'GPU', 'TPU', 'CUDA', 'ZenML', 'Prefect', 'Dagster', 'dbt', 'Data Build Tool', 'Great Expectations', 'Apache Iceberg', 'Delta Lake', 'Apache Hudi', 'Data Lakehouse', 'Data Lake', 'Data Warehouse', 'Data Mesh', 'Feature Store', 'Model Registry', 'BentoML', 'Seldon', 'Triton Inference Server', 'TorchServe', 'TFServing', 'LLMOps',

    // ============================================
    // WEB FRAMEWORKS & APIs
    // ============================================
    'FastAPI', 'Flask', 'Django', 'Express', 'Node.js', 'React', 'Vue', 'Angular', 'REST APIs', 'REST', 'GraphQL', 'gRPC', 'WebSockets', 'Uvicorn', 'Gunicorn', 'NGINX', 'Next.js', 'Nuxt.js', 'Svelte', 'SvelteKit', 'Remix', 'Astro', 'Gatsby', 'Hono', 'Fastify', 'NestJS', 'Spring Boot', 'Spring Framework', 'Quarkus', 'Micronaut', 'Ruby on Rails', 'Laravel', 'Symfony', 'Gin', 'Echo', 'Fiber', 'Actix', 'Axum', 'Rocket', 'htmx', 'tRPC', 'Tailwind CSS', 'Bootstrap', 'Material UI', 'Chakra UI', 'Shadcn UI', 'Ant Design', 'Redux', 'Zustand', 'Recoil', 'Tanstack Query', 'React Query', 'Vite', 'Webpack', 'Rollup', 'esbuild', 'Babel', 'Three.js', 'WebGL', 'WebAssembly', 'WASM', 'Electron', 'Tauri', 'React Native', 'Flutter', 'Ionic', 'Expo',

    // ============================================
    // DEVOPS & CONTAINERIZATION
    // ============================================
    'Docker', 'Kubernetes', 'Jenkins', 'CI/CD', 'CI/CD Pipelines', 'GitHub Actions', 'GitLab CI', 'CircleCI', 'Travis CI', 'Terraform', 'Ansible', 'Chef', 'Puppet', 'Containerization', 'Container Orchestration', 'Microservices', 'Helm', 'ArgoCD', 'FluxCD', 'GitOps', 'Pulumi', 'CloudFormation', 'Packer', 'Vagrant', 'Istio', 'Envoy', 'Linkerd', 'Service Mesh', 'Prometheus', 'Grafana', 'Loki', 'Jaeger', 'OpenTelemetry', 'Datadog', 'New Relic', 'Splunk', 'ELK Stack', 'Logstash', 'Harbor', 'Podman', 'Buildah', 'Skaffold', 'Kustomize', 'Crossplane', 'Vault', 'Consul', 'Nomad', 'SonarQube', 'Trivy', 'Snyk', 'OWASP',

    // ============================================
    // NETWORKING & NETWORK ENGINEERING
    // ============================================
    'TCP/IP', 'UDP', 'HTTP', 'HTTPS', 'HTTP/2', 'HTTP/3', 'DNS', 'DHCP', 'BGP', 'OSPF', 'MPLS', 'VPN', 'SD-WAN', 'SDN', 'Software Defined Networking', 'NFV', 'Network Function Virtualization', 'Load Balancing', 'Reverse Proxy', 'Forward Proxy', 'Firewall', 'NAT', 'VLAN', 'Subnetting', 'IPv4', 'IPv6', 'ICMP', 'ARP', 'SSH', 'FTP', 'SFTP', 'SMTP', 'IMAP', 'SNMP', 'NTP', 'LDAP', 'Active Directory', 'Cisco', 'Juniper', 'Palo Alto', 'Fortinet', 'Wireshark', 'Nmap', 'Network Monitoring', 'Network Security', 'Zero Trust', 'Bandwidth Management', 'QoS', 'CDN', 'Content Delivery Network', 'Proxy', 'API Gateway', 'WAF', 'Web Application Firewall', 'DDoS Protection', 'Network Automation', 'NetDevOps', 'Ansible Networking', 'NETCONF', 'RESTCONF', 'YANG', '5G', 'LTE', 'Wi-Fi', 'Ethernet', 'Network Topology', 'Network Architecture', 'Overlay Networks', 'Underlay Networks',

    // ============================================
    // FRONTEND DEVELOPMENT
    // ============================================
    'HTML', 'CSS', 'SASS', 'SCSS', 'LESS', 'CSS Modules', 'CSS-in-JS', 'Styled Components', 'Emotion', 'Responsive Design', 'Mobile-First Design', 'Progressive Web Apps', 'PWA', 'Web Components', 'Single Page Applications', 'SPA', 'Server-Side Rendering', 'SSR', 'Static Site Generation', 'SSG', 'Accessibility', 'WCAG', 'SEO', 'Web Performance', 'Core Web Vitals', 'Lazy Loading', 'Code Splitting', 'Tree Shaking', 'Browser DevTools', 'Cross-Browser Compatibility', 'UI/UX Design', 'Figma', 'Storybook', 'Design Systems', 'Animation', 'GSAP', 'Framer Motion', 'Canvas API', 'SVG', 'WebRTC', 'Service Workers', 'IndexedDB', 'LocalStorage', 'Web APIs', 'DOM Manipulation',

    // ============================================
    // BACKEND DEVELOPMENT
    // ============================================
    'API Design', 'RESTful APIs', 'API Documentation', 'Middleware', 'Authentication', 'Authorization', 'Session Management', 'Caching', 'Message Queues', 'RabbitMQ', 'Bull', 'Celery', 'Background Jobs', 'Webhooks', 'Event-Driven Architecture', 'CQRS', 'Event Sourcing', 'Domain-Driven Design', 'DDD', 'Hexagonal Architecture', 'Clean Architecture', 'Serverless', 'Serverless Functions', 'Edge Computing', 'Database Design', 'ORM', 'Prisma', 'SQLAlchemy', 'TypeORM', 'Sequelize', 'Hibernate', 'Connection Pooling', 'Database Migrations', 'Schema Design',

    // ============================================
    // FULLSTACK DEVELOPMENT
    // ============================================
    'Full-Stack Development', 'Fullstack', 'MERN Stack', 'MEAN Stack', 'LAMP Stack', 'JAMstack', 'T3 Stack', 'Monorepo', 'Turborepo', 'Nx', 'Lerna', 'API Integration', 'Third-Party Integrations', 'Payment Integration', 'Stripe', 'OAuth Integration', 'SSO', 'Single Sign-On', 'Multi-Tenancy', 'SaaS Development', 'CMS', 'Contentful', 'Sanity', 'Strapi', 'Headless CMS', 'E-commerce',

    // ============================================
    // SOFTWARE ENGINEERING
    // ============================================
    'System Design', 'Software Architecture', 'Design Patterns', 'SOLID Principles', 'Object-Oriented Programming', 'OOP', 'Functional Programming', 'Reactive Programming', 'Concurrency', 'Multithreading', 'Async Programming', 'Memory Management', 'Garbage Collection', 'Code Review', 'Refactoring', 'Technical Debt', 'Documentation', 'API Contracts', 'OpenAPI Specification', 'SDK Development', 'Library Development', 'Package Publishing', 'Semantic Versioning', 'Dependency Management', 'Performance Optimization', 'Profiling', 'Debugging', 'Algorithms', 'Data Structures', 'Computational Complexity', 'Big O Notation', 'Distributed Systems', 'Consensus Algorithms', 'CAP Theorem', 'Eventual Consistency', 'Service-Oriented Architecture', 'SOA', 'Event-Driven', 'Pub/Sub', 'Message Brokers', 'Inter-Process Communication', 'IPC', 'Protocol Buffers', 'Protobuf', 'Thrift', 'Avro',

    // ============================================
    // DEPLOYMENT & INFRASTRUCTURE
    // ============================================
    'Deployment', 'Blue-Green Deployment', 'Canary Deployment', 'Rolling Deployment', 'Zero Downtime Deployment', 'Feature Flags', 'Infrastructure as Code', 'IaC', 'Cloud-Native', 'Hybrid Cloud', 'Multi-Cloud', 'On-Premises', 'Bare Metal', 'Virtual Machines', 'Hypervisor', 'VMware', 'KVM', 'Auto Scaling', 'Horizontal Scaling', 'Vertical Scaling', 'Disaster Recovery', 'Backup & Restore', 'High Availability', 'Fault Tolerance', 'SLA', 'SLO', 'SLI', 'Uptime', 'Incident Management', 'On-Call', 'Runbooks', 'Chaos Engineering', 'Site Reliability Engineering', 'SRE', 'Platform Engineering', 'Internal Developer Platform', 'IDP',

    // ============================================
    // VERSION CONTROL & COLLABORATION
    // ============================================
    'Git', 'GitHub', 'GitLab', 'Bitbucket', 'Version Control', 'Jira', 'Confluence', 'Slack', 'Linear', 'Notion', 'Trello', 'Asana', 'Code Reviews', 'Pull Requests', 'Branching Strategies', 'GitFlow', 'Trunk-Based Development', 'Monorepos',

    // ============================================
    // TESTING & QUALITY
    // ============================================
    'Unit Testing', 'Integration Testing', 'End-to-End Testing', 'Load Testing', 'Performance Testing', 'Test-Driven Development', 'TDD', 'Pytest', 'Jest', 'Selenium', 'Cypress', 'Playwright', 'Vitest', 'Mocha', 'Chai', 'JUnit', 'TestNG', 'Mockito', 'k6', 'Locust', 'Artillery', 'Contract Testing', 'Pact', 'Snapshot Testing', 'Code Coverage', 'Static Analysis', 'Linting', 'ESLint', 'Prettier', 'Black', 'Ruff', 'MyPy', 'Type Checking', 'BDD', 'Behavior-Driven Development',

    // ============================================
    // DATA VISUALIZATION & BI
    // ============================================
    'Power BI', 'Tableau', 'Looker', 'Grafana', 'Kibana', 'D3.js', 'Chart.js', 'Metabase', 'Apache Superset', 'Redash', 'Observable', 'Streamlit', 'Dash', 'Panel', 'Gradio', 'Evidence',

    // ============================================
    // OPERATING SYSTEMS & TOOLS
    // ============================================
    'Linux', 'Unix', 'Ubuntu', 'CentOS', 'macOS', 'Windows', 'Shell Scripting', 'Linux Shell Scripting', 'Vim', 'VS Code', 'Visual Studio Code', 'PyCharm', 'Jupyter', 'Jupyter Notebook', 'Colab', 'Google Colab', 'IntelliJ IDEA', 'WebStorm', 'Neovim', 'Emacs', 'tmux', 'Zsh', 'Fish Shell', 'Windows Subsystem for Linux', 'WSL', 'Homebrew', 'Package Managers', 'Dotfiles',

    // ============================================
    // METHODOLOGIES & PRACTICES
    // ============================================
    'DevOps', 'Agile', 'Scrum', 'Kanban', 'Continuous Integration', 'Continuous Deployment', 'Continuous Training', 'CT', 'Infrastructure as Code', 'IaC', 'Monitoring', 'Logging', 'Observability', 'Scalability', 'High Availability', 'Load Balancing', 'Caching', 'Optimization', 'DevSecOps', 'Platform Engineering', 'FinOps', 'Cloud Cost Optimization', 'Shift Left', 'Pair Programming', 'Mob Programming', 'Extreme Programming', 'XP', 'SAFe', 'Shape Up', 'OKRs',

    // ============================================
    // DOMAIN AREAS
    // ============================================
    'Data Science', 'Data Analytics', 'Business Intelligence', 'Statistics', 'Mathematics', 'Computer Science', 'Software Engineering', 'Data Engineering', 'Analytics', 'Quantitative Analysis', 'Operations Research', 'Economics', 'STEM', 'Science', 'Technology', 'Engineering', 'Blockchain', 'Web3', 'Smart Contracts', 'DeFi', 'NFT', 'IoT', 'Internet of Things', 'Embedded Systems', 'Robotics', 'AR/VR', 'Augmented Reality', 'Virtual Reality', 'Game Development', 'Unity', 'Unreal Engine', 'Godot', 'FinTech', 'HealthTech', 'EdTech', 'HPC', 'High Performance Computing', 'Quantum Computing',

    // ============================================
    // SOFT SKILLS & COLLABORATION
    // ============================================
    'Cross-Functional Collaboration', 'Team Leadership', 'Technical Leadership', 'Mentorship', 'Communication Skills', 'Problem-Solving', 'Critical Thinking', 'Project Management', 'Stakeholder Management', 'Presentation Skills', 'Technical Writing', 'System Thinking', 'Architecture Review', 'Engineering Management', 'Hiring', 'Technical Interviews', 'Onboarding', 'Knowledge Sharing', 'Inner Source',

    // ============================================
    // SECURITY & COMPLIANCE
    // ============================================
    'Security', 'Cybersecurity', 'Authentication', 'Authorization', 'OAuth', 'JWT', 'SSL', 'TLS', 'Encryption', 'GDPR', 'HIPAA', 'Compliance', 'Penetration Testing', 'Pen Testing', 'Ethical Hacking', 'Vulnerability Assessment', 'SAST', 'DAST', 'Secret Management', 'PKI', 'mTLS', 'API Security', 'XSS', 'CSRF', 'SQL Injection', 'Security Audits', 'SOC 2', 'ISO 27001', 'PCI DSS', 'Identity and Access Management', 'IAM', 'RBAC', 'ABAC', 'Zero Trust Security', 'SIEM', 'Threat Modeling', 'Incident Response', 'CVE', 'SOC Operations', 'Security Operations Center', 'Quality Assurance', 'Quality Control', 'QA/QC', 'Incident Management', 'Network Security', 'Security Monitoring', 'Threat Detection', 'Threat Analysis',
    'Security Incident Investigation', 'Case Review', 'Metrics Reporting', 'SOAR', 'Playbook Development', 'Security Playbooks', 'Incident Response Lifecycle', 'Security Analytics', 'Log Analysis', 'Security Tools', 'Cybersecurity Best Practices', 'Vulnerability Management', 'Security Compliance', 'Security Reporting', 'Root Cause Analysis', 'Risk Assessment', 'Security Operations', 'ITIL', 'CISSP', 'GCFA', 'GCIH', 'Technical Troubleshooting', 'Security Platforms', 'Network Infrastructure', 'Alert Triage', 'Security Event Analysis', 'Operational Excellence', 'Process Improvement', 'Scheduling Coordination', 'IDS/IPS', 'Packet Analysis', 'Cisco Networking', 'Network Traffic Analysis', 'Network Architecture', 'Access Control Lists (ACL)', 'Secure Network Design', 'Proxy Servers', 'Network Access Control (NAC)', 'Endpoint Security', 'Wireless Security', 'Network Hardening', 'Secure Remote Access', 'Port Scanning', 'TCP Dump', 'DNS Security', 'Email Security', 'Intrusion Detection', 'Intrusion Prevention', 'Palo Alto Networks', 'Check Point Firewall', 'Cisco ASA', 'Juniper Networks', 'Cloud Networking', 'Hybrid Network Infrastructure', 'Network Automation', 'Zero Trust Architecture', 'Threat Hunting', 'Malware Analysis', 'Digital Forensics', 'SOC Monitoring', 'Security Event Correlation', 'Network Performance Monitoring', 'Server Administration', 'Linux Networking', 'Windows Server', 'Multi-Factor Authentication (MFA)', 'Data Loss Prevention (DLP)', 'Security Auditing', 'Patch Management', 'Cyber Threat Intelligence', 'MITRE ATT&CK Framework', 'Incident Escalation', 'Security Operations Workflow', 'Network Baseline Analysis', 'High Availability Networking', 'Disaster Recovery', 'Business Continuity', 'Cloud Security', 'AWS Networking', 'Azure Networking', 'Google Cloud Networking', 'Virtualization', 'Hyper-V', 'Container Security', 'Kubernetes Networking', 'Network Segmentation', 'SOC Automation', 'Bash Scripting', 'Python for Networking', 'PowerShell', 'Syslog', 'NetFlow', 'Endpoint Detection and Response (EDR)', 'Extended Detection and Response (XDR)', 'Security Orchestration', 'Authentication Protocols', 'Kerberos', 'RADIUS', 'TACACS+', 'Security Awareness', 'Compliance Frameworks', 'NIST Cybersecurity Framework', 'PCI-DSS', 'HIPAA Security', 'Governance, Risk & Compliance (GRC)',

    // ============================================
    // ADDITIONAL TOOLS & TECHNOLOGIES
    // ============================================
    'Postman', 'Swagger', 'OpenAPI', 'Makefile', 'CMake', 'Gradle', 'Maven', 'npm', 'pip', 'conda', 'Poetry', 'Virtual Environments', 'Environment Management', 'pnpm', 'yarn', 'Bun', 'Deno', 'nvm', 'pyenv', 'asdf', 'Bazel', 'Buck', 'Nx Build', 'Turborepo', 'Bruno', 'Insomnia', 'ngrok', 'LocalStack', 'Minio', 'Temporal', 'Conductor', 'n8n', 'Zapier', 'Make',

    // ============================================
    // BUSINESS ANALYST
    // ============================================
    'Business Analyst', 'Business Analysis', 'Requirements Gathering', 'Requirement Analysis', 'Business Requirements Document', 'BRD', 'Functional Requirements', 'Non-Functional Requirements', 'Stakeholder Management', 'Stakeholder Communication', 'Gap Analysis', 'Process Improvement', 'Business Process Modeling',
    'BPMN', 'Workflow Analysis', 'Use Cases', 'User Stories', 'Acceptance Criteria', 'Agile', 'Scrum', 'Kanban', 'SDLC', 'Waterfall', 'Sprint Planning', 'Backlog Management', 'Jira', 'Confluence', 'Trello', 'Asana', 'Notion', 'Project Management', 'Change Management', 'Risk Analysis', 'Risk Management', 'Root Cause Analysis', 'SWOT Analysis', 'PESTLE Analysis', 'Feasibility Analysis', 'Cost Benefit Analysis', 'Business Process Reengineering', 'Process Mapping', 'Data Analysis', 'Data Visualization', 'Dashboarding', 'Reporting', 'KPI Tracking', 'KPI Analysis', 'Metrics Reporting', 'Performance Metrics', 'SQL', 'Excel', 'Advanced Excel', 'Pivot Tables', 'VLOOKUP', 'XLOOKUP', 'Power Query', 'Macros', 'Power BI',
    'Tableau', 'Looker', 'Google Data Studio', 'Data Cleaning', 'Data Validation', 'ETL', 'Data Warehousing', 'Data Modeling', 'Relational Databases', 'MySQL', 'PostgreSQL', 'Oracle', 'SQL Server', 'CRM', 'ERP', 'Salesforce', 'SAP', 'Microsoft Dynamics', 'ServiceNow', 'UAT', 'User Acceptance Testing', 'Test Cases', 'Test Scenarios', 'QA Collaboration', 'Documentation', 'Technical Documentation', 'Business Documentation', 'Functional Specifications', 'Wireframing', 'Mockups', 'Figma', 'Lucidchart', 'Visio', 'Draw.io', 'Process Documentation', 'API Understanding', 'REST APIs', 'JSON', 'XML', 'Integration Requirements', 'Vendor Management', 'Client Communication', 'Cross-Functional Collaboration', 'Presentation Skills', 'Problem Solving', 'Critical Thinking', 'Decision Making', 'Analytical Thinking', 'Strategic Planning', 'Business Intelligence', 'Forecasting', 'Trend Analysis', 'Market Research', 'Competitive Analysis', 'Financial Analysis', 'Budget Analysis', 'Operations Analysis', 'Customer Journey Mapping', 'User Experience Analysis', 'Digital Transformation', 'Automation', 'Compliance', 'GDPR', 'HIPAA', 'Regulatory Requirements', 'KYC', 'AML', 'Banking Domain', 'Healthcare Domain', 'Retail Domain', 'E-commerce', 'FinTech', 'Product Management Collaboration', 'Roadmap Planning', 'Release Planning', 'Change Requests', 'Dependency Management', 'Meeting Facilitation', 'Workshop Facilitation', 'Interview Techniques', 'Survey Analysis', 'Documentation Review', 'Business Rules', 'Decision Trees', 'Data Governance', 'Master Data Management', 'Data Quality', 'Process Optimization', 'Operational Excellence', 'Continuous Improvement', 'Lean', 'Six Sigma', 'DMAIC', 'Customer Requirements', 'Business Strategy', 'Digital Business Analysis', 'Enterprise Analysis', 'Solution Design', 'Solution Evaluation', 'Requirement Traceability Matrix', 'RTM', 'Business Case Development', 'Scenario Analysis', 'Process Automation', 'RPA', 'UiPath', 'Blue Prism', 'Automation Anywhere',

    // ============================================
    // PRODUCT OWNER
    // ============================================
    'Product Owner', 'Product Management', 'Agile Product Management', 'Scrum', 'Agile', 'Kanban', 'SAFe', 'Product Strategy', 'Product Vision', 'Product Roadmap', 'Roadmap Planning', 'Backlog Management', 'Product Backlog', 'Sprint Planning', 'Sprint Reviews', 'Sprint Retrospectives', 'User Stories', 'Acceptance Criteria', 'Epics', 'Themes', 'Feature Prioritization', 'Prioritization Frameworks', 'MoSCoW', 'RICE', 'WSJF', 'Stakeholder Management', 'Stakeholder Communication',
    'Cross-Functional Collaboration', 'Requirements Gathering', 'Requirement Analysis', 'Business Requirements', 'Functional Requirements', 'Market Research', 'Competitive Analysis', 'Customer Research', 'Customer Feedback', 'User-Centric Design', 'Customer Journey Mapping', 'User Experience', 'UX', 'Product Discovery', 'Product Delivery', 'Go-To-Market Strategy', 'GTM', 'Product Lifecycle Management', 'MVP', 'Minimum Viable Product', 'Feature Definition', 'Feature Flagging', 'Release Planning', 'Release Management', 'Product Metrics', 'KPI Tracking', 'OKRs', 'Data-Driven Decision Making', 'Analytics', 'A/B Testing', 'Experimentation', 'Growth Metrics', 'Conversion Optimization', 'Retention Metrics', 'Engagement Metrics', 'Business Intelligence', 'Product Analytics', 'Mixpanel', 'Amplitude', 'Google Analytics', 'Heap Analytics', 'Hotjar', 'SQL', 'Excel', 'Power BI', 'Tableau', 'Jira', 'Confluence', 'Trello', 'Asana', 'Notion', 'Miro', 'Figma', 'Lucidchart', 'Product Documentation', 'Technical Documentation', 'Wireframing', 'Mockups', 'Prototype Development', 'API Understanding', 'REST APIs', 'GraphQL',
    'SaaS Products', 'B2B Products', 'B2C Products', 'Platform Products', 'Mobile Products', 'Web Products', 'Digital Products', 'Product Operations', 'Business Analysis', 'Risk Management', 'Dependency Management', 'Change Management', 'Roadmap Prioritization', 'Customer Success', 'Customer Experience', 'Product Adoption', 'Product Launch', 'Feature Rollout', 'Innovation', 'Strategic Planning', 'Decision Making', 'Problem Solving', 'Leadership', 'Team Collaboration', 'Technical Collaboration', 'Engineering Collaboration', 'Design Collaboration', 'QA Collaboration', 'DevOps Awareness', 'CI/CD Awareness', 'Cloud Products', 'AI Products', 'Machine Learning Products', 'FinTech', 'HealthTech', 'E-commerce', 'EdTech', 'Retail Tech', 'Digital Transformation', 'Operational Excellence', 'Continuous Improvement', 'Lean Product Development', 'Lean Startup', 'Design Thinking', 'Scrum Ceremonies', 'Story Mapping', 'Use Cases', 'Acceptance Testing', 'UAT', 'Product Ownership', 'Vision Alignment', 'Stakeholder Alignment', 'Revenue Growth', 'Monetization Strategy', 'Pricing Strategy', 'Customer Retention', 'Product Scaling', 'Enterprise Products', 'Platform Strategy', 'Product Innovation', 'Data Governance', 'Security Compliance', 'GDPR', 'HIPAA', 'SOC 2', 'Product Quality', 'Feature Validation', 'Roadmap Execution', 'Product KPIs', 'Business Strategy', 'Digital Strategy', 'Operational Strategy',

    // ============================================
    // HEALTHCARE BUSINESS ANALYST
    // ============================================
    'Healthcare Business Analyst', 'Healthcare BA', 'Healthcare Domain', 'Healthcare IT', 'Healthcare Analytics', 'Business Analysis', 'Requirements Gathering', 'Requirement Analysis', 'Business Requirements Document', 'BRD', 'Functional Requirements', 'Non-Functional Requirements', 'Stakeholder Management', 'Stakeholder Communication', 'Process Improvement', 'Gap Analysis', 'Workflow Analysis', 'Business Process Modeling', 'BPMN', 'Use Cases', 'User Stories', 'Acceptance Criteria', 'Agile', 'Scrum', 'Kanban', 'SDLC', 'Waterfall', 'Jira', 'Confluence', 'Project Management', 'Healthcare Operations', 'Clinical Workflows', 'Patient Management', 'Electronic Health Records', 'EHR', 'Electronic Medical Records', 'EMR', 'Epic Systems', 'Cerner', 'MEDITECH', 'Allscripts', 'Healthcare Information Systems', 'Hospital Information Systems', 'HIS', 'Practice Management Systems', 'Revenue Cycle Management', 'RCM', 'Claims Processing', 'Medical Billing', 'Medical Coding', 'ICD-10', 'CPT Codes', 'HCPCS', 'HL7', 'FHIR', 'Healthcare Interoperability', 'Clinical Data Integration', 'Health Information Exchange', 'HIE', 'Patient Data Management', 'Clinical Documentation', 'Healthcare Compliance', 'HIPAA', 'HITECH', 'Healthcare Regulations', 'Data Privacy', 'PHI', 'Protected Health Information', 'Clinical Decision Support', 'Care Coordination', 'Patient Journey Mapping', 'Healthcare KPIs', 'Healthcare Reporting', 'Healthcare Dashboards', 'Data Analysis', 'Healthcare Data Analytics', 'Data Visualization', 'SQL', 'Excel', 'Advanced Excel', 'Power BI', 'Tableau', 'Looker', 'Data Cleaning', 'Data Validation', 'ETL', 'Healthcare Data Warehousing', 'Population Health Management', 'Value-Based Care', 'Telemedicine', 'Telehealth', 'Clinical Research',
    'Healthcare Quality Assurance', 'Healthcare Quality Improvement', 'Risk Management', 'Root Cause Analysis', 'UAT', 'User Acceptance Testing', 'Test Cases', 'Test Scenarios', 'QA Collaboration', 'Documentation', 'Technical Documentation', 'Functional Specifications', 'Process Documentation', 'Workflow Documentation', 'Wireframing', 'Mockups', 'Figma', 'Visio', 'Lucidchart', 'API Understanding', 'REST APIs', 'JSON', 'XML', 'Healthcare Integrations', 'Vendor Management', 'Client Communication', 'Cross-Functional Collaboration', 'Problem Solving', 'Critical Thinking', 'Decision Making', 'Analytical Thinking', 'Strategic Planning', 'Business Intelligence', 'Forecasting', 'Trend Analysis', 'Operational Excellence', 'Continuous Improvement', 'Lean', 'Six Sigma', 'DMAIC', 'Healthcare Transformation', 'Digital Health', 'HealthTech', 'Remote Patient Monitoring', 'Clinical Operations', 'Scheduling Coordination', 'Insurance Verification', 'Claims Adjudication', 'Prior Authorization', 'Patient Engagement', 'Healthcare CRM', 'Customer Experience', 'Case Management', 'Utilization Management', 'Clinical Analytics', 'Data Governance', 'Master Data Management', 'Data Quality', 'Regulatory Reporting', 'Compliance Audits', 'Healthcare Security', 'Access Control', 'Identity and Access Management', 'IAM', 'Healthcare Risk Assessment', 'Process Optimization', 'Business Strategy', 'Enterprise Analysis', 'Solution Evaluation', 'Requirement Traceability Matrix', 'RTM', 'Business Case Development', 'Scenario Analysis', 'Automation', 'RPA', 'UiPath', 'Automation Anywhere', 'Blue Prism',

    // ============================================
    // TELECOM BUSINESS ANALYST
    // ============================================
    'Telecom Business Analyst', 'Telecom BA', 'Telecommunications', 'Telecom Domain', 'Telecom Operations', 'Business Analysis', 'Requirements Gathering', 'Requirement Analysis', 'Business Requirements Document', 'BRD', 'Functional Requirements', 'Non-Functional Requirements', 'Stakeholder Management', 'Stakeholder Communication', 'Gap Analysis', 'Process Improvement', 'Workflow Analysis', 'Business Process Modeling', 'BPMN', 'Use Cases', 'User Stories', 'Acceptance Criteria', 'Agile', 'Scrum', 'Kanban', 'SDLC', 'Waterfall', 'Jira', 'Confluence', 'Project Management', 'Telecom Billing', 'OSS', 'Operational Support Systems', 'BSS', 'Business Support Systems', 'CRM', 'Customer Relationship Management', 'Order Management', 'Service Fulfillment', 'Service Assurance', 'Provisioning', 'Network Operations', 'NOC', 'Telecom Analytics', 'Subscriber Management', 'SIM Management', 'Mobile Network Operations', 'Fixed Line Operations', 'Broadband Services', 'Fiber Optics', 'FTTH', '5G', '4G LTE', 'LTE', 'VoLTE', 'VoIP', 'IMS', 'IP Multimedia Subsystem', 'Wireless Networks', 'Mobile Networks', 'Network Optimization', 'Network Planning', 'RF Planning', 'Spectrum Management', 'Telecom Infrastructure', 'Network Architecture', 'Telecom Integration', 'API Integration', 'REST APIs', 'SOAP APIs', 'JSON', 'XML', 'HLR', 'HSS', 'PCRF', 'Charging Systems', 'Mediation Systems', 'Billing Systems', 'Revenue Assurance', 'Fraud Management', 'Roaming', 'Interconnect Billing', 'Subscriber Data Management', 'Customer Experience', 'Customer Journey Mapping', 'KPI Tracking', 'Telecom KPIs', 'SLA Management', 'Service Level Agreements', 'Incident Management', 'Problem Management', 'ITIL', 'Change Management', 'Risk Management', 'Root Cause Analysis',
    'Data Analysis', 'SQL', 'Advanced Excel', 'Power BI', 'Tableau', 'Looker', 'Data Visualization', 'Dashboarding', 'Reporting', 'ETL', 'Data Warehousing', 'Big Data', 'Kafka', 'Hadoop', 'Spark', 'Cloud Computing', 'AWS', 'Azure', 'Google Cloud', 'Network Security', 'Cybersecurity', 'Firewall', 'VPN', 'IAM', 'Identity and Access Management', 'Telecom Compliance', 'Regulatory Compliance', 'TRAI', 'FCC', 'GDPR', 'UAT', 'User Acceptance Testing', 'Test Cases', 'QA Collaboration', 'Documentation', 'Technical Documentation', 'Functional Specifications', 'Process Documentation', 'Wireframing', 'Figma', 'Visio', 'Lucidchart', 'Vendor Management', 'Client Communication', 'Cross-Functional Collaboration', 'Problem Solving', 'Critical Thinking', 'Analytical Thinking', 'Strategic Planning', 'Business Intelligence', 'Forecasting', 'Trend Analysis', 'Operational Excellence', 'Continuous Improvement', 'Lean', 'Six Sigma', 'DMAIC', 'Digital Transformation', 'Telecom Transformation', 'IoT', 'Internet of Things', 'M2M', 'Machine-to-Machine', 'Edge Computing', 'Cloud-Native Networks', 'NFV', 'Network Function Virtualization', 'SDN', 'Software Defined Networking', 'Network Automation', 'Automation', 'RPA', 'UiPath', 'Blue Prism', 'Automation Anywhere', 'Enterprise Analysis', 'Solution Evaluation', 'Requirement Traceability Matrix', 'RTM', 'Business Case Development', 'Scenario Analysis', 'Product Lifecycle Management', 'Service Delivery', 'Customer Retention', 'Churn Analysis', 'Revenue Growth', 'Digital Channels', 'Self-Service Portals',

    // ============================================
    // AI ENGINEER / LLM / RAG / AGENTIC AI / MLOPS
    // ============================================
    'AI Engineer', 'Artificial Intelligence', 'AI', 'Machine Learning', 'Deep Learning', 'Generative AI', 'GenAI', 'Large Language Models', 'LLMs', 'Foundation Models', 'GPT', 'BERT', 'Transformers', 'Hugging Face', 'Hugging Face Transformers', 'Prompt Engineering', 'Prompt Tuning', 'Instruction Tuning', 'Fine-Tuning', 'Supervised Fine-Tuning', 'SFT', 'Transfer Learning', 'RLHF', 'Reinforcement Learning from Human Feedback', 'DPO', 'LoRA', 'QLoRA', 'PEFT', 'Quantization', 'Model Compression', 'Knowledge Distillation', 'Embeddings', 'Vector Embeddings', 'Semantic Search', 'Retrieval-Augmented Generation', 'RAG', 'Hybrid Search', 'Vector Search', 'Dense Retrieval', 'Sparse Retrieval', 'Reranking', 'Context Engineering', 'Context Window Optimization', 'Chunking', 'Document Parsing', 'Document Intelligence', 'OCR', 'Tokenization', 'NER', 'Named Entity Recognition', 'Text Classification', 'Sentiment Analysis', 'Summarization', 'Question Answering', 'Chatbots', 'Conversational AI', 'AI Assistants', 'AI Agents', 'Agentic AI', 'Autonomous Agents', 'Multi-Agent Systems', 'Tool Calling', 'Function Calling', 'Workflow Automation', 'Reasoning Models', 'Chain-of-Thought', 'Tree-of-Thought', 'Reflection Agents', 'Planning Agents', 'Memory Systems', 'Long-Term Memory', 'Short-Term Memory', 'LangChain', 'LangGraph', 'LlamaIndex', 'CrewAI', 'AutoGen', 'Semantic Kernel', 'DSPy', 'Haystack', 'OpenAI SDK', 'Anthropic SDK', 'Cohere', 'LiteLLM', 'Ollama', 'vLLM', 'Inference Optimization', 'TensorRT', 'ONNX', 'ONNX Runtime', 'Triton Inference Server', 'TorchServe', 'TFServing', 'DeepSpeed', 'Megatron', 'CUDA', 'GPU', 'TPU', 'Distributed Training', 'Multi-GPU Training', 'Model Parallelism', 'Data Parallelism', 'PyTorch', 'TensorFlow', 'Keras', 'JAX', 'Scikit-Learn', 'XGBoost', 'LightGBM', 'CatBoost',
    'spaCy', 'NLTK', 'Gensim', 'FastAPI', 'Flask', 'Django', 'REST APIs', 'GraphQL', 'gRPC', 'WebSockets', 'Microservices', 'Docker', 'Kubernetes', 'Containerization', 'CI/CD', 'GitHub Actions', 'GitLab CI', 'Jenkins', 'Terraform', 'Ansible', 'Cloud Computing', 'AWS', 'Amazon Web Services', 'Azure', 'Microsoft Azure', 'GCP', 'Google Cloud Platform', 'SageMaker', 'Vertex AI', 'Azure OpenAI', 'Bedrock', 'Databricks', 'MLflow', 'Weights & Biases', 'Weights and Biases', 'DVC', 'Kubeflow', 'ZenML', 'Prefect', 'Dagster', 'Apache Airflow', 'MLOps', 'LLMOps', 'Model Deployment', 'Model Monitoring', 'Model Evaluation', 'Evaluation Metrics', 'Benchmarking', 'A/B Testing', 'Experiment Tracking', 'Feature Store', 'Model Registry', 'Drift Detection', 'Data Drift', 'Model Drift', 'Observability', 'OpenTelemetry', 'Prometheus', 'Grafana', 'Logging', 'Monitoring', 'Inference Pipelines', 'Real-Time Inference', 'Batch Inference', 'Streaming Pipelines', 'Apache Kafka', 'Spark', 'PySpark', 'ETL', 'Data Pipelines', 'Data Engineering', 'Data Lake', 'Data Warehouse', 'BigQuery', 'Snowflake', 'Redshift', 'PostgreSQL', 'MongoDB', 'Redis', 'Vector Databases', 'VectorDBs', 'Pinecone', 'Weaviate', 'Milvus', 'Chroma', 'Qdrant', 'FAISS', 'Neo4j', 'Knowledge Graphs', 'GraphRAG', 'SQL', 'Python', 'TypeScript', 'JavaScript', 'Go', 'Linux', 'Shell Scripting', 'Bash', 'Git', 'GitHub', 'System Design', 'Software Architecture', 'Distributed Systems', 'Scalability', 'High Availability', 'Caching', 'Message Queues', 'RabbitMQ', 'Celery', 'Async Programming', 'Event-Driven Architecture', 'Security', 'API Security', 'Authentication', 'Authorization', 'OAuth', 'JWT', 'Responsible AI', 'AI Safety', 'Explainability', 'Interpretability', 'XAI', 'Bias Detection', 'Fairness', 'Multimodal AI', 'Vision-Language Models', 'Speech Recognition', 'Text-to-Speech', 'Computer Vision', 'Image Classification', 'Object Detection', 'Document AI', 'Automation', 'Process Automation', 'RPA', 'Technical Documentation', 'Problem Solving', 'Analytical Thinking', 'Cross-Functional Collaboration', 'Research and Development', 'Production AI Systems', 'AI Infrastructure', 'Inference Infrastructure', 'Cloud-Native AI', 'Serverless AI', 'Edge AI', 'AI Product Development',

    // ============================================================
    // SYSTEMS ENGINEER / DESKTOP ENGINEER
    // ============================================================
    'Windows Server 2016', 'Windows Server 2019', 'Windows Server 2022', 'IIS', 'DNS', 'DHCP', 'DFS', 'WSUS', 'File Services', 'Server Hardening', 'Patch Management', 'High Availability', 'Failover Clustering', 'Disaster Recovery', 'RTO', 'RPO', 'Capacity Planning', 'Terraform', 'PowerShell DSC', 'SCOM', 'Microsoft Intune', 'MDM', 'MAM', 'SCCM', 'MECM', 'Jamf Pro', 'macOS MDM', 'iOS MDM', 'Windows Autopilot', 'Zero-Touch Provisioning', 'Apple Business Manager', 'Apple DEP', 'WDS', 'MDT', 'FileVault', 'BitLocker', 'Gatekeeper', 'Apple Silicon', 'M1', 'M2', 'M3', 'macOS Ventura', 'macOS Sonoma', 'Windows 10', 'Windows 11', 'Cross-Platform Compliance', 'Patch Compliance', 'Device Enrollment', 'Software Deployment', 'Active Directory', 'AD DS', 'Azure AD', 'Entra ID', 'Group Policy', 'GPO', 'Conditional Access', 'MFA', 'RBAC', 'PIM', 'LAPS', 'Jamf Directory Integration', 'Microsoft 365', 'Exchange Online', 'Microsoft Teams', 'SharePoint', 'OneDrive', 'Microsoft Defender for Endpoint', 'DLP', 'Azure Monitor', 'Azure Virtual Desktop', 'AVD', 'ARM', 'FSLogix', 'Zero Trust', 'IAM', 'OU Hierarchies', 'VMware vSphere', 'VMware vCenter', 'VMware ESXi', 'Hyper-V', 'VM Templates', 'Snapshots', 'Resource Pools', 'vMotion', 'Citrix Virtual Apps', 'Citrix Virtual Desktops', 'VMware Horizon', 'FSLogix Profile Containers', 'PowerShell', 'PowerShell Automation', 'Bash', 'Python', 'API Queries', 'KQL', 'Log Analytics', 'Grafana', 'SolarWinds', 'Datadog', 'PagerDuty', 'Power BI', 'Compliance Dashboards', 'CIS Benchmarks', 'CIS Level 1 Hardening', 'NIST 800-53', 'EDR', 'SIEM', 'Vulnerability Remediation', 'Encryption Compliance', 'Security Audit', 'ServiceNow', 'Incident Management', 'Change Management', 'CMDB', 'Asset Management', 'Jira', 'ITIL 4', 'TCP/IP', 'VLAN', 'VPN', 'Cisco AnyConnect', 'GlobalProtect', '802.1x NAC', 'Wi-Fi', 'LAN', 'WAN', 'Confluence', 'Tier 2 Support', 'Tier 3 Support', 'SLA Management', 'CSAT', 'CompTIA A+', 'ITIL 4 Foundation', 'Enterprise IT Infrastructure', 'End-User Computing', 'EUC', 'Hardware Asset Lifecycle', 'Documentation', 'Remote Device Management',


    // ============================================================
    // BUSINESS ANALYST / PRODUCT OWNER
    // ============================================================
    'Business Requirements Gathering', 'BRD Documentation', 'FRD Documentation', 'User Stories', 'Epics', 'Acceptance Criteria Definition', 'Gap Analysis', 'Process Flow Diagrams', 'Functional Specifications', 'Use Cases', 'Non-Functional Requirements', 'Requirements Traceability Matrix', 'Current-State Mapping', 'Future-State Mapping', 'Product Backlog Management', 'Sprint Planning', 'Backlog Grooming', 'Agile', 'Scrum', 'Release Planning', 'Dependency Management', 'Roadmap Planning', 'Sprint Reviews', 'Retrospectives', 'Sprint Velocity Tracking', 'Sprint Metrics Tracking', 'Release Management', 'UAT Planning', 'UAT Execution', 'Test Case Review', 'Test Scenario Design', 'Defect Tracking', 'QA Validation', 'Post-Deployment Validation', 'REST APIs', 'API Integration Documentation', 'Data Mapping', 'Microservices Architecture', 'Middleware', 'SaaS Platforms', 'Cloud-Based Applications', 'System Integrations', 'HIPAA Compliance', 'HITECH Compliance', 'PHI Data Governance', 'Audit Trail Specifications', 'Access Control Requirements', 'Regulatory Compliance', 'Healthcare Claims Adjudication', 'Member Eligibility Verification', 'Prior Authorization Workflows', 'Explanation of Benefits (EOB)', 'Provider Network Management', 'Medical Billing Workflows', 'Telecom Systems', 'Network Provisioning', 'Billing Platform', 'Customer Self-Service Portal', 'Enterprise Account Management', 'Jira', 'Confluence', 'Miro', 'Figma', 'Power BI', 'Tableau', 'Microsoft Excel', 'PowerPoint', 'Google Sheets', 'AI-Assisted Requirement Tools', 'SLA Monitoring', 'SLO Monitoring', 'Delivery Performance Analysis', 'Stakeholder Management', 'Cross-Functional Collaboration', 'Executive Reporting', 'Process Documentation', 'Implementation Plans', 'Release Notes', 'Knowledge Transfer', 'SQL', 'JavaScript', 'Predictive Analytics',

    // ============================================================
    // DESKTOP ENGINEER / SYSTEMS ENGINEER
    // ============================================================
    'Microsoft Intune', 'Jamf Pro', 'SCCM', 'MECM', 'Apple Business Manager', 'ABM', 'Windows Autopilot', 'Apple DEP', 'MDM', 'WDS', 'MDT', 'Zero-Touch Provisioning', 'Device Compliance', 'Policy Drift Remediation', 'Software Deployment', 'Application Packaging', 'Endpoint Patching', 'Patch Compliance', 'Patch Management', 'Cross-Platform Endpoint Management', 'Windows 10', 'Windows 11', 'Windows Server 2016', 'Windows Server 2019', 'macOS Monterey', 'macOS Ventura', 'macOS Sonoma', 'iOS', 'Ubuntu Linux', 'OS Migration', 'Windows 10 to Windows 11 Migration', 'Hardware Compatibility Validation', 'Active Directory', 'Azure AD', 'Entra ID', 'Group Policy', 'GPO', 'OU Design', 'RBAC', 'MFA', 'Conditional Access', 'SSO', 'LDAP', 'User Lifecycle Provisioning', 'Identity Management', 'IAM', 'Microsoft Azure', 'Azure Virtual Desktop', 'AVD', 'VMware vSphere', 'Hyper-V', 'AWS EC2', 'VM Management', 'Resource Allocation', 'VDI Optimization', 'Exchange Online', 'Microsoft Teams', 'SharePoint', 'OneDrive', 'Microsoft Defender for Endpoint', 'Purview DLP', 'Microsoft Purview', 'Microsoft 365', 'PowerShell', 'Python', 'Bash', 'Batch Scripting', 'Ansible', 'REST APIs', 'Automation Scripts', 'Endpoint Remediation', 'Software Audits', 'CIS Benchmarks', 'NIST SP 800-171', 'BitLocker', 'FileVault', 'Endpoint Protection', 'Security Hardening', 'Security Posture', 'Vulnerability Remediation', 'Symantec Endpoint Protection', 'ServiceNow', 'Jira Service Management', 'Zendesk', 'Freshservice', 'ITSM', 'ITIL 4', 'SLA Compliance', 'Self-Service IT Portal', 'Ticket Management', 'SolarWinds', 'Nagios', 'Splunk', 'Azure Monitor', 'Event Viewer', 'Wireshark', 'Proactive Monitoring', 'TCP/IP', 'DNS', 'DHCP', 'VPN', 'Cisco AnyConnect', 'Wi-Fi Troubleshooting', 'LAN', 'WAN', 'NetApp', 'Veeam', 'Backup Operations', 'Disaster Recovery', 'RTO', 'Asset Management', 'Hardware Asset Audit', 'CMDB', 'Tier 2 Support', 'Tier 3 Support', 'First-Call Resolution', 'CSAT', 'Knowledge Base', 'SOPs', 'Technical Documentation', 'New Hire Onboarding', 'IT Orientation', 'Vendor Management', 'Warranty Management', 'Microsoft Certified Modern Desktop Administrator Associate', 'MD-102', 'Apple Certified Support Professional', 'ACSP', 'Jamf Certified Associate', 'CompTIA A+', 'CompTIA Network+', 'ITIL 4 Foundation', 'Certificate Lifecycle Management', 'Print Server Management', 'Apple Configurator 2',

    // ============================================================
    // IT SUPPORT SPECIALIST / DESKTOP ENGINEER
    // ============================================================
    'Level 1 Support', 'Level 2 Support', 'Helpdesk Support', 'Tier 1 Support', 'Tier 2 Support', 'Incident Management', 'Request Fulfilment', 'SLA Compliance', 'SLA Tracking', 'Escalation Management', 'First-Contact Resolution', 'CSAT', 'Root Cause Analysis', 'Troubleshooting', 'ServiceNow', 'Jira Service Management', 'Zendesk', 'Freshservice', 'ITSM', 'ITIL 4', 'Knowledge Base', 'SOPs', 'Self-Service IT Portal', 'SQL', 'MySQL', 'DBMS', 'CMDB Asset Reporting', 'SCCM SQL Reporting', 'IT Asset Database Queries', 'ServiceNow Data Extraction', 'Inventory Dashboard Generation', 'Patch Compliance Reports', 'Software Distribution Audit', 'AI-Assisted Incident Detection', 'AI-Driven Log Correlation', 'Anomaly Detection', 'Predictive Maintenance Monitoring', 'Pattern Recognition', 'AI Knowledge Base Suggestion Tools', 'Microsoft Intune', 'Jamf Pro', 'SCCM', 'MECM', 'Apple DEP', 'Apple Business Manager', 'ABM', 'MDM', 'WDS', 'MDT', 'Windows Autopilot', 'System Imaging', 'Device Configuration', 'Zero-Touch Provisioning', 'Endpoint Compliance', 'Patch Management', 'Software Deployment', 'Application Packaging', 'Windows 10', 'Windows 11', 'Windows Server 2016', 'Windows Server 2019', 'macOS Monterey', 'macOS Ventura', 'macOS Sonoma', 'iOS',
    'Android', 'OS Deployment', 'OS Migration', 'Windows 11 Migration', 'Hardware Compatibility Scripts', 'Active Directory', 'Azure AD', 'Entra ID', 'Group Policy', 'GPO', 'Conditional Access', 'MFA', 'User Lifecycle Provisioning', 'Onboarding', 'Offboarding', 'Password Resets', 'Access Provisioning', 'Microsoft 365', 'Outlook', 'Microsoft Teams', 'SharePoint', 'OneDrive', 'Exchange Online', 'Azure Virtual Desktop', 'AVD', 'Hybrid Work Support', 'CIS Benchmarks', 'BitLocker', 'FileVault 2', 'Symantec Endpoint Protection', 'IT Policy Compliance', 'Security Hardening', 'Endpoint Protection', 'Laptops', 'Desktops', 'Mobile Devices', 'Tablets', 'Printers', 'Hardware Inventory', 'IT Asset Lifecycle', 'Warranty Coordination', 'DBMS-Backed Asset Tracking', 'Asset Audit', 'TCP/IP', 'DNS', 'DHCP', 'VPN', 'Cisco AnyConnect', 'Wi-Fi', 'LAN', 'WAN', 'Comm Room Patching', 'Network Troubleshooting', 'Print Server Management', 'Driver Deployment via GPO', 'Technical Documentation', 'End-User Communication', 'Vendor Management', 'Cross-Functional Collaboration', 'Global Support Teams', 'Financial Services IT', 'Banking IT', 'ITIL 4 Foundation', 'CompTIA A+', 'CompTIA Network+', 'Microsoft MD-102', 'Modern Desktop Administrator', 'Apple Certified Support Professional', 'ACSP', 'Jamf Certified Associate',
];

/**
 * Extract technical keywords from text using the pattern list
 * @param {string} text - Text to extract keywords from
 * @returns {Array<string>} - Array of found keywords
 */
function extractTechnicalKeywords(text) {
    if (!text) return [];

    const textLower = text.toLowerCase();
    const foundKeywords = [];

    for (const pattern of TECHNICAL_PATTERNS) {
        const regex = new RegExp(`\\b${pattern}\\b`, 'gi');
        if (regex.test(textLower)) {
            // Normalize the keyword (remove regex escapes)
            const normalized = pattern.replace(/\\b|\\+|\\/g, '').replace(/\s+/g, ' ');
            if (!foundKeywords.includes(normalized)) {
                foundKeywords.push(normalized);
            }
        }
    }

    return foundKeywords.sort();
}

/**
 * Find common keywords between two sets
 * @param {Array<string>} set1 - First keyword set
 * @param {Array<string>} set2 - Second keyword set
 * @returns {Array<string>} - Common keywords
 */
function findCommonKeywords(set1, set2) {
    const set1Lower = new Set(set1.map(k => k.toLowerCase()));
    return set2.filter(k => set1Lower.has(k.toLowerCase()));
}

/**
 * Find missing keywords (in set2 but not in set1)
 * @param {Array<string>} set1 - First keyword set (e.g., resume)
 * @param {Array<string>} set2 - Second keyword set (e.g., JD)
 * @returns {Array<string>} - Missing keywords
 */
function findMissingKeywords(set1, set2) {
    const set1Lower = new Set(set1.map(k => k.toLowerCase()));
    return set2.filter(k => !set1Lower.has(k.toLowerCase()));
}

module.exports = {
    TECHNICAL_PATTERNS,
    extractTechnicalKeywords,
    findCommonKeywords,
    findMissingKeywords
};
