/**
 * Technical Keyword Patterns
 * 
 * Comprehensive list of technical keywords for matching resumes and job descriptions.
 * This is a static list that can be imported and used across the application.
 * 
 * Usage:
 *   const { TECHNICAL_PATTERNS } = require('./technicalPatterns');
 *   const keywords = extractKeywords(text, TECHNICAL_PATTERNS);
 */

/**
 * Comprehensive technical keyword patterns
 * Includes programming languages, frameworks, tools, cloud services, databases, etc.
 */
// const TECHNICAL_PATTERNS = [

//   // ============================================
//   // PROGRAMMING LANGUAGES
//   // ============================================

//   'Python',
//   'SQL',
//   'Java',
//   'JavaScript',
//   'TypeScript',
//   'Go',
//   'Golang',
//   'C',
//   'C\\+\\+',
//   'C#',
//   'Scala',
//   'R',
//   'Ruby',
//   'PHP',
//   'Swift',
//   'Kotlin',
//   'Rust',
//   'Bash',
//   'Shell',
//   'PowerShell',

//   // ============================================
//   // ML/AI FRAMEWORKS & LIBRARIES
//   // ============================================

//   'PyTorch',
//   'TensorFlow',
//   'Keras',
//   'Scikit-Learn',
//   'Scikit Learn',
//   'XGBoost',
//   'LightGBM',
//   'CatBoost',
//   'Hugging Face',
//   'Hugging Face Transformers',
//   'LangChain',
//   'LlamaIndex',
//   'JAX',
//   'MXNet',
//   'Caffe',
//   'ONNX',
//   'OpenCV',
//   'spaCy',
//   'NLTK',
//   'Gensim',
//   'FastAI',

//   // ============================================
//   // DATA SCIENCE LIBRARIES
//   // ============================================

//   'NumPy',
//   'Pandas',
//   'SciPy',
//   'Matplotlib',
//   'Seaborn',
//   'Plotly',
//   'Bokeh',
//   'Dask',
//   'Polars',

//   // ============================================
//   // CLOUD PLATFORMS & SERVICES
//   // ============================================

//   'AWS',
//   'Amazon Web Services',
//   'Azure',
//   'Microsoft Azure',
//   'GCP',
//   'Google Cloud',
//   'Google Cloud Platform',
//   'S3',
//   'EC2',
//   'Lambda',
//   'SageMaker',
//   'Azure ML',
//   'Azure Data Factory',
//   'Azure OpenAI',
//   'Blob Storage',
//   'AKS',
//   'EKS',
//   'GKE',
//   'Cloud Computing',
//   'Cloud Computing Platforms',
//   'Vertex AI',
//   'Bedrock',

//   // ============================================
//   // DATABASES
//   // ============================================

//   'PostgreSQL',
//   'MySQL',
//   'MongoDB',
//   'Redis',
//   'Cassandra',
//   'Elasticsearch',
//   'Snowflake',
//   'BigQuery',
//   'Redshift',
//   'DynamoDB',
//   'CosmosDB',
//   'SQL Server',
//   'Oracle',
//   'SQLite',
//   'Neo4j',
//   'VectorDBs',
//   'Vector Databases',
//   'Pinecone',
//   'Weaviate',
//   'Milvus',
//   'Chroma',
//   'Qdrant',
//   'FAISS',
//   'Graph Databases',
//   'Relational Databases',
//   'NoSQL',

//   // ============================================
//   // AI/ML CONCEPTS
//   // ============================================

//   'Machine Learning',
//   'Deep Learning',
//   'Natural Language Processing',
//   'NLP',
//   'Computer Vision',
//   'Large Language Models',
//   'LLMs',
//   'GPT',
//   'BERT',
//   'GPT-Style Models',
//   'Transformers',
//   'Generative AI',
//   'GenAI',
//   'AI',
//   'Artificial Intelligence',
//   'Prompt Engineering',
//   'Retrieval-Augmented Generation',
//   'RAG',
//   'Fine-Tuning',
//   'Transfer Learning',
//   'Zero-Shot Learning',
//   'Few-Shot Learning',
//   'Embeddings',
//   'Semantic Search',
//   'Entity Extraction',
//   'Tokenization',
//   'Sentiment Analysis',
//   'Classification',
//   'Clustering',
//   'Regression',
//   'Time Series',
//   'Forecasting',
//   'Anomaly Detection',
//   'Recommendation Systems',
//   'Reinforcement Learning',
//   'Supervised Learning',
//   'Unsupervised Learning',
//   'Semi-Supervised Learning',
//   'Neural Networks',
//   'CNNs',
//   'RNNs',
//   'LSTMs',
//   'GANs',
//   'Autoencoders',
//   'Object Detection',
//   'Image Classification',
//   'Feature Extraction',
//   'Feature Engineering',
//   'Feature Selection',
//   'Hyperparameter Tuning',
//   'Model Training',
//   'Model Evaluation',
//   'Model Deployment',
//   'Model Monitoring',
//   'Model Versioning',
//   'Drift Detection',
//   'Data Drift',
//   'Model Drift',
//   'A/B Testing',
//   'Experimentation',
//   'Evaluation Metrics',
//   'Evaluation Metric Frameworks',
//   'Benchmarking',
//   'Ablation Studies',

//   // ============================================
//   // MLOPS & DATA ENGINEERING
//   // ============================================

//   'MLOps',
//   'MLflow',
//   'Weights & Biases',
//   'Weights and Biases',
//   'DVC',
//   'Airflow',
//   'Apache Airflow',
//   'Kubeflow',
//   'Apache Spark',
//   'PySpark',
//   'Spark',
//   'Kafka',
//   'Apache Kafka',
//   'Flink',
//   'Hadoop',
//   'Hive',
//   'Presto',
//   'Databricks',
//   'ETL',
//   'ETL Pipelines',
//   'Data Pipelines',
//   'Data Engineering',
//   'Data Ingestion',
//   'Batch Processing',
//   'Stream Processing',
//   'Real-Time Processing',
//   'Distributed Processing',
//   'Distributed Training',
//   'Multi-GPU Training',
//   'GPU',
//   'TPU',
//   'CUDA',

//   // ============================================
//   // WEB FRAMEWORKS & APIs
//   // ============================================

//   'FastAPI',
//   'Flask',
//   'Django',
//   'Express',
//   'Node.js',
//   'React',
//   'Vue',
//   'Angular',
//   'REST APIs',
//   'REST',
//   'GraphQL',
//   'gRPC',
//   'WebSockets',
//   'Uvicorn',
//   'Gunicorn',
//   'NGINX',

//   // ============================================
//   // DEVOPS & CONTAINERIZATION
//   // ============================================

//   'Docker',
//   'Kubernetes',
//   'Jenkins',
//   'CI/CD',
//   'CI/CD Pipelines',
//   'GitHub Actions',
//   'GitLab CI',
//   'CircleCI',
//   'Travis CI',
//   'Terraform',
//   'Ansible',
//   'Chef',
//   'Puppet',
//   'Containerization',
//   'Container Orchestration',
//   'Microservices',

//   // ============================================
//   // VERSION CONTROL & COLLABORATION
//   // ============================================

//   'Git',
//   'GitHub',
//   'GitLab',
//   'Bitbucket',
//   'Version Control',
//   'Jira',
//   'Confluence',
//   'Slack',

//   // ============================================
//   // TESTING & QUALITY
//   // ============================================

//   'Unit Testing',
//   'Integration Testing',
//   'End-to-End Testing',
//   'Load Testing',
//   'Performance Testing',
//   'Test-Driven Development',
//   'TDD',
//   'Pytest',
//   'Jest',
//   'Selenium',
//   'Cypress',

//   // ============================================
//   // DATA VISUALIZATION & BI
//   // ============================================

//   'Power BI',
//   'Tableau',
//   'Looker',
//   'Grafana',
//   'Kibana',
//   'D3.js',
//   'Chart.js',

//   // ============================================
//   // OPERATING SYSTEMS & TOOLS
//   // ============================================

//   'Linux',
//   'Unix',
//   'Ubuntu',
//   'CentOS',
//   'macOS',
//   'Windows',
//   'Shell Scripting',
//   'Linux Shell Scripting',
//   'Vim',
//   'VS Code',
//   'Visual Studio Code',
//   'PyCharm',
//   'Jupyter',
//   'Jupyter Notebook',
//   'Colab',
//   'Google Colab',

//   // ============================================
//   // METHODOLOGIES & PRACTICES
//   // ============================================

//   'DevOps',
//   'Agile',
//   'Scrum',
//   'Kanban',
//   'Continuous Integration',
//   'Continuous Deployment',
//   'Continuous Training',
//   'CT',
//   'Infrastructure as Code',
//   'IaC',
//   'Monitoring',
//   'Logging',
//   'Observability',
//   'Scalability',
//   'High Availability',
//   'Load Balancing',
//   'Caching',
//   'Optimization',

//   // ============================================
//   // DOMAIN AREAS
//   // ============================================

//   'Data Science',
//   'Data Analytics',
//   'Business Intelligence',
//   'Statistics',
//   'Mathematics',
//   'Computer Science',
//   'Software Engineering',
//   'Data Engineering',
//   'Analytics',
//   'Quantitative Analysis',
//   'Operations Research',
//   'Economics',
//   'STEM',
//   'Science',
//   'Technology',
//   'Engineering',

//   // ============================================
//   // SOFT SKILLS & COLLABORATION
//   // ============================================

//   'Cross-Functional Collaboration',
//   'Team Leadership',
//   'Technical Leadership',
//   'Mentorship',
//   'Communication Skills',
//   'Problem-Solving',
//   'Critical Thinking',
//   'Project Management',
//   'Stakeholder Management',
//   'Presentation Skills',

//   // ============================================
//   // SECURITY & COMPLIANCE
//   // ============================================

//   'Security',
//   'Cybersecurity',
//   'Authentication',
//   'Authorization',
//   'OAuth',
//   'JWT',
//   'SSL',
//   'TLS',
//   'Encryption',
//   'GDPR',
//   'HIPAA',
//   'Compliance',

//   // ============================================
//   // ADDITIONAL TOOLS & TECHNOLOGIES
//   // ============================================

//   'Postman',
//   'Swagger',
//   'OpenAPI',
//   'Makefile',
//   'CMake',
//   'Gradle',
//   'Maven',
//   'npm',
//   'pip',
//   'conda',
//   'Poetry',
//   'Virtual Environments',
//   'Environment Management'

// ];

const TECHNICAL_PATTERNS = [

  // ============================================
  // PROGRAMMING LANGUAGES
  // ============================================

  'Python',
  'SQL',
  'Java',
  'JavaScript',
  'TypeScript',
  'Go',
  'Golang',
  'C',
  'C\\+\\+',
  'C#',
  'Scala',
  'R',
  'Ruby',
  'PHP',
  'Swift',
  'Kotlin',
  'Rust',
  'Bash',
  'Shell',
  'PowerShell',
  'Perl',
  'Lua',
  'Haskell',
  'Elixir',
  'Erlang',
  'Clojure',
  'F#',
  'MATLAB',
  'Julia',
  'Groovy',
  'Dart',
  'Objective-C',
  'Assembly',
  'COBOL',
  'Fortran',
  'Solidity',
  'Zig',
  'Nim',
  'Crystal',
  'OCaml',

  // ============================================
  // ML/AI FRAMEWORKS & LIBRARIES
  // ============================================

  'PyTorch',
  'TensorFlow',
  'Keras',
  'Scikit-Learn',
  'Scikit Learn',
  'XGBoost',
  'LightGBM',
  'CatBoost',
  'Hugging Face',
  'Hugging Face Transformers',
  'LangChain',
  'LlamaIndex',
  'JAX',
  'MXNet',
  'Caffe',
  'ONNX',
  'OpenCV',
  'spaCy',
  'NLTK',
  'Gensim',
  'FastAI',
  'Stable Diffusion',
  'Diffusers',
  'AutoML',
  'H2O.ai',
  'Ray',
  'Ray Tune',
  'Optuna',
  'Triton',
  'TensorRT',
  'DeepSpeed',
  'Megatron',
  'CrewAI',
  'AutoGen',
  'Semantic Kernel',
  'OpenAI SDK',
  'Anthropic SDK',
  'Cohere',
  'LiteLLM',
  'Ollama',
  'vLLM',

  // ============================================
  // DATA SCIENCE LIBRARIES
  // ============================================

  'NumPy',
  'Pandas',
  'SciPy',
  'Matplotlib',
  'Seaborn',
  'Plotly',
  'Bokeh',
  'Dask',
  'Polars',
  'Statsmodels',
  'SymPy',
  'NetworkX',
  'Arrow',
  'PyArrow',
  'Great Expectations',

  // ============================================
  // CLOUD PLATFORMS & SERVICES
  // ============================================

  'AWS',
  'Amazon Web Services',
  'Azure',
  'Microsoft Azure',
  'GCP',
  'Google Cloud',
  'Google Cloud Platform',
  'S3',
  'EC2',
  'Lambda',
  'SageMaker',
  'Azure ML',
  'Azure Data Factory',
  'Azure OpenAI',
  'Blob Storage',
  'AKS',
  'EKS',
  'GKE',
  'Cloud Computing',
  'Cloud Computing Platforms',
  'Vertex AI',
  'Bedrock',
  'DigitalOcean',
  'Heroku',
  'Linode',
  'Cloudflare',
  'Vercel',
  'Netlify',
  'Railway',
  'Render',
  'Fly.io',
  'IBM Cloud',
  'Oracle Cloud',
  'Alibaba Cloud',
  'CloudFront',
  'Route 53',
  'IAM',
  'VPC',
  'RDS',
  'ECS',
  'ECR',
  'SNS',
  'SQS',
  'Kinesis',
  'Glue',
  'Athena',
  'EMR',

  // ============================================
  // DATABASES
  // ============================================

  'PostgreSQL',
  'MySQL',
  'MongoDB',
  'Redis',
  'Cassandra',
  'Elasticsearch',
  'Snowflake',
  'BigQuery',
  'Redshift',
  'DynamoDB',
  'CosmosDB',
  'SQL Server',
  'Oracle',
  'SQLite',
  'Neo4j',
  'VectorDBs',
  'Vector Databases',
  'Pinecone',
  'Weaviate',
  'Milvus',
  'Chroma',
  'Qdrant',
  'FAISS',
  'Graph Databases',
  'Relational Databases',
  'NoSQL',
  'MariaDB',
  'CockroachDB',
  'TimescaleDB',
  'InfluxDB',
  'Prometheus',
  'Clickhouse',
  'Couchbase',
  'HBase',
  'Memcached',
  'Supabase',
  'PlanetScale',
  'Neon',
  'Firebase',
  'Firestore',
  'Airtable',
  'RethinkDB',
  'ArangoDB',

  // ============================================
  // AI/ML CONCEPTS
  // ============================================

  'Machine Learning',
  'Deep Learning',
  'Natural Language Processing',
  'NLP',
  'Computer Vision',
  'Large Language Models',
  'LLMs',
  'GPT',
  'BERT',
  'GPT-Style Models',
  'Transformers',
  'Generative AI',
  'GenAI',
  'AI',
  'Artificial Intelligence',
  'Prompt Engineering',
  'Retrieval-Augmented Generation',
  'RAG',
  'Fine-Tuning',
  'Transfer Learning',
  'Zero-Shot Learning',
  'Few-Shot Learning',
  'Embeddings',
  'Semantic Search',
  'Entity Extraction',
  'Tokenization',
  'Sentiment Analysis',
  'Classification',
  'Clustering',
  'Regression',
  'Time Series',
  'Forecasting',
  'Anomaly Detection',
  'Recommendation Systems',
  'Reinforcement Learning',
  'Supervised Learning',
  'Unsupervised Learning',
  'Semi-Supervised Learning',
  'Neural Networks',
  'CNNs',
  'RNNs',
  'LSTMs',
  'GANs',
  'Autoencoders',
  'Object Detection',
  'Image Classification',
  'Feature Extraction',
  'Feature Engineering',
  'Feature Selection',
  'Hyperparameter Tuning',
  'Model Training',
  'Model Evaluation',
  'Model Deployment',
  'Model Monitoring',
  'Model Versioning',
  'Drift Detection',
  'Data Drift',
  'Model Drift',
  'A/B Testing',
  'Experimentation',
  'Evaluation Metrics',
  'Evaluation Metric Frameworks',
  'Benchmarking',
  'Ablation Studies',
  'Agentic AI',
  'AI Agents',
  'Multi-Agent Systems',
  'Chain-of-Thought',
  'Instruction Tuning',
  'RLHF',
  'Reinforcement Learning from Human Feedback',
  'DPO',
  'LoRA',
  'QLoRA',
  'PEFT',
  'Quantization',
  'Model Compression',
  'Knowledge Distillation',
  'Explainability',
  'Interpretability',
  'XAI',
  'Responsible AI',
  'AI Safety',
  'Bias Detection',
  'Fairness',
  'Multimodal AI',
  'Vision-Language Models',
  'Speech Recognition',
  'Text-to-Speech',
  'OCR',
  'Document AI',
  'Graph Neural Networks',
  'GNNs',
  'Attention Mechanisms',
  'Self-Supervised Learning',
  'Contrastive Learning',
  'Foundation Models',

  // ============================================
  // MLOPS & DATA ENGINEERING
  // ============================================

  'MLOps',
  'MLflow',
  'Weights & Biases',
  'Weights and Biases',
  'DVC',
  'Airflow',
  'Apache Airflow',
  'Kubeflow',
  'Apache Spark',
  'PySpark',
  'Spark',
  'Kafka',
  'Apache Kafka',
  'Flink',
  'Hadoop',
  'Hive',
  'Presto',
  'Databricks',
  'ETL',
  'ETL Pipelines',
  'Data Pipelines',
  'Data Engineering',
  'Data Ingestion',
  'Batch Processing',
  'Stream Processing',
  'Real-Time Processing',
  'Distributed Processing',
  'Distributed Training',
  'Multi-GPU Training',
  'GPU',
  'TPU',
  'CUDA',
  'ZenML',
  'Prefect',
  'Dagster',
  'dbt',
  'Data Build Tool',
  'Great Expectations',
  'Apache Iceberg',
  'Delta Lake',
  'Apache Hudi',
  'Data Lakehouse',
  'Data Lake',
  'Data Warehouse',
  'Data Mesh',
  'Feature Store',
  'Model Registry',
  'BentoML',
  'Seldon',
  'Triton Inference Server',
  'TorchServe',
  'TFServing',
  'LLMOps',

  // ============================================
  // WEB FRAMEWORKS & APIs
  // ============================================

  'FastAPI',
  'Flask',
  'Django',
  'Express',
  'Node.js',
  'React',
  'Vue',
  'Angular',
  'REST APIs',
  'REST',
  'GraphQL',
  'gRPC',
  'WebSockets',
  'Uvicorn',
  'Gunicorn',
  'NGINX',
  'Next.js',
  'Nuxt.js',
  'Svelte',
  'SvelteKit',
  'Remix',
  'Astro',
  'Gatsby',
  'Hono',
  'Fastify',
  'NestJS',
  'Spring Boot',
  'Spring Framework',
  'Quarkus',
  'Micronaut',
  'Ruby on Rails',
  'Laravel',
  'Symfony',
  'Gin',
  'Echo',
  'Fiber',
  'Actix',
  'Axum',
  'Rocket',
  'htmx',
  'tRPC',
  'Tailwind CSS',
  'Bootstrap',
  'Material UI',
  'Chakra UI',
  'Shadcn UI',
  'Ant Design',
  'Redux',
  'Zustand',
  'Recoil',
  'Tanstack Query',
  'React Query',
  'Vite',
  'Webpack',
  'Rollup',
  'esbuild',
  'Babel',
  'Three.js',
  'WebGL',
  'WebAssembly',
  'WASM',
  'Electron',
  'Tauri',
  'React Native',
  'Flutter',
  'Ionic',
  'Expo',

  // ============================================
  // DEVOPS & CONTAINERIZATION
  // ============================================

  'Docker',
  'Kubernetes',
  'Jenkins',
  'CI/CD',
  'CI/CD Pipelines',
  'GitHub Actions',
  'GitLab CI',
  'CircleCI',
  'Travis CI',
  'Terraform',
  'Ansible',
  'Chef',
  'Puppet',
  'Containerization',
  'Container Orchestration',
  'Microservices',
  'Helm',
  'ArgoCD',
  'FluxCD',
  'GitOps',
  'Pulumi',
  'CloudFormation',
  'Packer',
  'Vagrant',
  'Istio',
  'Envoy',
  'Linkerd',
  'Service Mesh',
  'Prometheus',
  'Grafana',
  'Loki',
  'Jaeger',
  'OpenTelemetry',
  'Datadog',
  'New Relic',
  'Splunk',
  'ELK Stack',
  'Logstash',
  'Harbor',
  'Podman',
  'Buildah',
  'Skaffold',
  'Kustomize',
  'Crossplane',
  'Vault',
  'Consul',
  'Nomad',
  'SonarQube',
  'Trivy',
  'Snyk',
  'OWASP',

  // ============================================
  // NETWORKING & NETWORK ENGINEERING
  // ============================================

  'TCP/IP',
  'UDP',
  'HTTP',
  'HTTPS',
  'HTTP/2',
  'HTTP/3',
  'DNS',
  'DHCP',
  'BGP',
  'OSPF',
  'MPLS',
  'VPN',
  'SD-WAN',
  'SDN',
  'Software Defined Networking',
  'NFV',
  'Network Function Virtualization',
  'Load Balancing',
  'Reverse Proxy',
  'Forward Proxy',
  'Firewall',
  'NAT',
  'VLAN',
  'Subnetting',
  'IPv4',
  'IPv6',
  'ICMP',
  'ARP',
  'SSH',
  'FTP',
  'SFTP',
  'SMTP',
  'IMAP',
  'SNMP',
  'NTP',
  'LDAP',
  'Active Directory',
  'Cisco',
  'Juniper',
  'Palo Alto',
  'Fortinet',
  'Wireshark',
  'Nmap',
  'Network Monitoring',
  'Network Security',
  'Zero Trust',
  'Bandwidth Management',
  'QoS',
  'CDN',
  'Content Delivery Network',
  'Proxy',
  'API Gateway',
  'WAF',
  'Web Application Firewall',
  'DDoS Protection',
  'Network Automation',
  'NetDevOps',
  'Ansible Networking',
  'NETCONF',
  'RESTCONF',
  'YANG',
  '5G',
  'LTE',
  'Wi-Fi',
  'Ethernet',
  'Network Topology',
  'Network Architecture',
  'Overlay Networks',
  'Underlay Networks',

  // ============================================
  // FRONTEND DEVELOPMENT
  // ============================================

  'HTML',
  'CSS',
  'SASS',
  'SCSS',
  'LESS',
  'CSS Modules',
  'CSS-in-JS',
  'Styled Components',
  'Emotion',
  'Responsive Design',
  'Mobile-First Design',
  'Progressive Web Apps',
  'PWA',
  'Web Components',
  'Single Page Applications',
  'SPA',
  'Server-Side Rendering',
  'SSR',
  'Static Site Generation',
  'SSG',
  'Accessibility',
  'WCAG',
  'SEO',
  'Web Performance',
  'Core Web Vitals',
  'Lazy Loading',
  'Code Splitting',
  'Tree Shaking',
  'Browser DevTools',
  'Cross-Browser Compatibility',
  'UI/UX Design',
  'Figma',
  'Storybook',
  'Design Systems',
  'Animation',
  'GSAP',
  'Framer Motion',
  'Canvas API',
  'SVG',
  'WebRTC',
  'Service Workers',
  'IndexedDB',
  'LocalStorage',
  'Web APIs',
  'DOM Manipulation',

  // ============================================
  // BACKEND DEVELOPMENT
  // ============================================

  'API Design',
  'RESTful APIs',
  'API Documentation',
  'Middleware',
  'Authentication',
  'Authorization',
  'Session Management',
  'Caching',
  'Message Queues',
  'RabbitMQ',
  'Bull',
  'Celery',
  'Background Jobs',
  'Webhooks',
  'Event-Driven Architecture',
  'CQRS',
  'Event Sourcing',
  'Domain-Driven Design',
  'DDD',
  'Hexagonal Architecture',
  'Clean Architecture',
  'Serverless',
  'Serverless Functions',
  'Edge Computing',
  'Database Design',
  'ORM',
  'Prisma',
  'SQLAlchemy',
  'TypeORM',
  'Sequelize',
  'Hibernate',
  'Connection Pooling',
  'Database Migrations',
  'Schema Design',

  // ============================================
  // FULLSTACK DEVELOPMENT
  // ============================================

  'Full-Stack Development',
  'Fullstack',
  'MERN Stack',
  'MEAN Stack',
  'LAMP Stack',
  'JAMstack',
  'T3 Stack',
  'Monorepo',
  'Turborepo',
  'Nx',
  'Lerna',
  'API Integration',
  'Third-Party Integrations',
  'Payment Integration',
  'Stripe',
  'OAuth Integration',
  'SSO',
  'Single Sign-On',
  'Multi-Tenancy',
  'SaaS Development',
  'CMS',
  'Contentful',
  'Sanity',
  'Strapi',
  'Headless CMS',
  'E-commerce',

  // ============================================
  // SOFTWARE ENGINEERING
  // ============================================

  'System Design',
  'Software Architecture',
  'Design Patterns',
  'SOLID Principles',
  'Object-Oriented Programming',
  'OOP',
  'Functional Programming',
  'Reactive Programming',
  'Concurrency',
  'Multithreading',
  'Async Programming',
  'Memory Management',
  'Garbage Collection',
  'Code Review',
  'Refactoring',
  'Technical Debt',
  'Documentation',
  'API Contracts',
  'OpenAPI Specification',
  'SDK Development',
  'Library Development',
  'Package Publishing',
  'Semantic Versioning',
  'Dependency Management',
  'Performance Optimization',
  'Profiling',
  'Debugging',
  'Algorithms',
  'Data Structures',
  'Computational Complexity',
  'Big O Notation',
  'Distributed Systems',
  'Consensus Algorithms',
  'CAP Theorem',
  'Eventual Consistency',
  'Service-Oriented Architecture',
  'SOA',
  'Event-Driven',
  'Pub/Sub',
  'Message Brokers',
  'Inter-Process Communication',
  'IPC',
  'Protocol Buffers',
  'Protobuf',
  'Thrift',
  'Avro',

  // ============================================
  // DEPLOYMENT & INFRASTRUCTURE
  // ============================================

  'Deployment',
  'Blue-Green Deployment',
  'Canary Deployment',
  'Rolling Deployment',
  'Zero Downtime Deployment',
  'Feature Flags',
  'Infrastructure as Code',
  'IaC',
  'Cloud-Native',
  'Hybrid Cloud',
  'Multi-Cloud',
  'On-Premises',
  'Bare Metal',
  'Virtual Machines',
  'Hypervisor',
  'VMware',
  'KVM',
  'Auto Scaling',
  'Horizontal Scaling',
  'Vertical Scaling',
  'Disaster Recovery',
  'Backup & Restore',
  'High Availability',
  'Fault Tolerance',
  'SLA',
  'SLO',
  'SLI',
  'Uptime',
  'Incident Management',
  'On-Call',
  'Runbooks',
  'Chaos Engineering',
  'Site Reliability Engineering',
  'SRE',
  'Platform Engineering',
  'Internal Developer Platform',
  'IDP',

  // ============================================
  // VERSION CONTROL & COLLABORATION
  // ============================================

  'Git',
  'GitHub',
  'GitLab',
  'Bitbucket',
  'Version Control',
  'Jira',
  'Confluence',
  'Slack',
  'Linear',
  'Notion',
  'Trello',
  'Asana',
  'Code Reviews',
  'Pull Requests',
  'Branching Strategies',
  'GitFlow',
  'Trunk-Based Development',
  'Monorepos',

  // ============================================
  // TESTING & QUALITY
  // ============================================

  'Unit Testing',
  'Integration Testing',
  'End-to-End Testing',
  'Load Testing',
  'Performance Testing',
  'Test-Driven Development',
  'TDD',
  'Pytest',
  'Jest',
  'Selenium',
  'Cypress',
  'Playwright',
  'Vitest',
  'Mocha',
  'Chai',
  'JUnit',
  'TestNG',
  'Mockito',
  'k6',
  'Locust',
  'Artillery',
  'Contract Testing',
  'Pact',
  'Snapshot Testing',
  'Code Coverage',
  'Static Analysis',
  'Linting',
  'ESLint',
  'Prettier',
  'Black',
  'Ruff',
  'MyPy',
  'Type Checking',
  'BDD',
  'Behavior-Driven Development',

  // ============================================
  // DATA VISUALIZATION & BI
  // ============================================

  'Power BI',
  'Tableau',
  'Looker',
  'Grafana',
  'Kibana',
  'D3.js',
  'Chart.js',
  'Metabase',
  'Apache Superset',
  'Redash',
  'Observable',
  'Streamlit',
  'Dash',
  'Panel',
  'Gradio',
  'Evidence',

  // ============================================
  // OPERATING SYSTEMS & TOOLS
  // ============================================

  'Linux',
  'Unix',
  'Ubuntu',
  'CentOS',
  'macOS',
  'Windows',
  'Shell Scripting',
  'Linux Shell Scripting',
  'Vim',
  'VS Code',
  'Visual Studio Code',
  'PyCharm',
  'Jupyter',
  'Jupyter Notebook',
  'Colab',
  'Google Colab',
  'IntelliJ IDEA',
  'WebStorm',
  'Neovim',
  'Emacs',
  'tmux',
  'Zsh',
  'Fish Shell',
  'Windows Subsystem for Linux',
  'WSL',
  'Homebrew',
  'Package Managers',
  'Dotfiles',

  // ============================================
  // METHODOLOGIES & PRACTICES
  // ============================================

  'DevOps',
  'Agile',
  'Scrum',
  'Kanban',
  'Continuous Integration',
  'Continuous Deployment',
  'Continuous Training',
  'CT',
  'Infrastructure as Code',
  'IaC',
  'Monitoring',
  'Logging',
  'Observability',
  'Scalability',
  'High Availability',
  'Load Balancing',
  'Caching',
  'Optimization',
  'DevSecOps',
  'Platform Engineering',
  'FinOps',
  'Cloud Cost Optimization',
  'Shift Left',
  'Pair Programming',
  'Mob Programming',
  'Extreme Programming',
  'XP',
  'SAFe',
  'Shape Up',
  'OKRs',

  // ============================================
  // DOMAIN AREAS
  // ============================================

  'Data Science',
  'Data Analytics',
  'Business Intelligence',
  'Statistics',
  'Mathematics',
  'Computer Science',
  'Software Engineering',
  'Data Engineering',
  'Analytics',
  'Quantitative Analysis',
  'Operations Research',
  'Economics',
  'STEM',
  'Science',
  'Technology',
  'Engineering',
  'Blockchain',
  'Web3',
  'Smart Contracts',
  'DeFi',
  'NFT',
  'IoT',
  'Internet of Things',
  'Embedded Systems',
  'Robotics',
  'AR/VR',
  'Augmented Reality',
  'Virtual Reality',
  'Game Development',
  'Unity',
  'Unreal Engine',
  'Godot',
  'FinTech',
  'HealthTech',
  'EdTech',
  'HPC',
  'High Performance Computing',
  'Quantum Computing',

  // ============================================
  // SOFT SKILLS & COLLABORATION
  // ============================================

  'Cross-Functional Collaboration',
  'Team Leadership',
  'Technical Leadership',
  'Mentorship',
  'Communication Skills',
  'Problem-Solving',
  'Critical Thinking',
  'Project Management',
  'Stakeholder Management',
  'Presentation Skills',
  'Technical Writing',
  'System Thinking',
  'Architecture Review',
  'Engineering Management',
  'Hiring',
  'Technical Interviews',
  'Onboarding',
  'Knowledge Sharing',
  'Inner Source',

  // ============================================
  // SECURITY & COMPLIANCE
  // ============================================

  'Security',
  'Cybersecurity',
  'Authentication',
  'Authorization',
  'OAuth',
  'JWT',
  'SSL',
  'TLS',
  'Encryption',
  'GDPR',
  'HIPAA',
  'Compliance',
  'Penetration Testing',
  'Pen Testing',
  'Ethical Hacking',
  'Vulnerability Assessment',
  'SAST',
  'DAST',
  'Secret Management',
  'PKI',
  'mTLS',
  'API Security',
  'XSS',
  'CSRF',
  'SQL Injection',
  'Security Audits',
  'SOC 2',
  'ISO 27001',
  'PCI DSS',
  'Identity and Access Management',
  'IAM',
  'RBAC',
  'ABAC',
  'Zero Trust Security',
  'SIEM',
  'Threat Modeling',
  'Incident Response',
  'CVE',
  'SOC Operations',
'Security Operations Center',
'Quality Assurance',
'Quality Control',
'QA/QC',
'Incident Response',
'Incident Management',
'Cybersecurity',
'Network Security',
'Security Monitoring',
'Threat Detection',
'Threat Analysis',
'Security Incident Investigation',
'Case Review',
'Metrics Reporting',
'SIEM',
'SOAR',
'Playbook Development',
'Security Playbooks',
'Incident Response Lifecycle',
'Security Analytics',
'Log Analysis',
'Security Tools',
'Cybersecurity Best Practices',
'Vulnerability Management',
'Security Compliance',
'Security Reporting',
'Root Cause Analysis',
'Risk Assessment',
'Security Operations',
'ITIL',
'CISSP',
'GCFA',
'GCIH',
'Cross-Functional Collaboration',
'Technical Troubleshooting',
'Security Platforms',
'Network Infrastructure',
'Alert Triage',
'Security Event Analysis',
'Operational Excellence',
'Documentation',
'Process Improvement',
'Scheduling Coordination',
'TCP/IP',
'UDP',
'DNS',
'DHCP',
'HTTP/HTTPS',
'SSL/TLS',
'VPN',
'LAN/WAN',
'Routing & Switching',
'Network Troubleshooting',
'Network Protocols',
'Firewall Management',
'IDS/IPS',
'Packet Analysis',
'Wireshark',
'Cisco Networking',
'Network Traffic Analysis',
'Network Architecture',
'Subnetting',
'VLAN',
'NAT',
'Access Control Lists (ACL)',
'Secure Network Design',
'Proxy Servers',
'Network Access Control (NAC)',
'Endpoint Security',
'Wireless Security',
'Network Hardening',
'Secure Remote Access',
'Port Scanning',
'Nmap',
'TCP Dump',
'DNS Security',
'Email Security',
'Intrusion Detection',
'Intrusion Prevention',
'Palo Alto Networks',
'Fortinet',
'Check Point Firewall',
'Cisco ASA',
'Juniper Networks',
'Cloud Networking',
'Hybrid Network Infrastructure',
'Network Automation',
'SD-WAN',
'Zero Trust Architecture',
'Threat Hunting',
'Malware Analysis',
'Digital Forensics',
'SOC Monitoring',
'Security Event Correlation',
'Network Performance Monitoring',
'Server Administration',
'Linux Networking',
'Windows Server',
'Active Directory',
'IAM (Identity & Access Management)',
'Multi-Factor Authentication (MFA)',
'Data Loss Prevention (DLP)',
'Security Auditing',
'Patch Management',
'Penetration Testing',
'Cyber Threat Intelligence',
'MITRE ATT&CK Framework',
'Incident Escalation',
'Security Operations Workflow',
'Network Baseline Analysis',
'High Availability Networking',
'Load Balancing',
'Disaster Recovery',
'Business Continuity',
'Cloud Security',
'AWS Networking',
'Azure Networking',
'Google Cloud Networking',
'Virtualization',
'VMware',
'Hyper-V',
'Container Security',
'Kubernetes Networking',
'Network Segmentation',
'SOC Automation',
'Bash Scripting',
'Python for Networking',
'PowerShell',
'REST APIs',
'Syslog',
'SNMP',
'NetFlow',
'Endpoint Detection and Response (EDR)',
'Extended Detection and Response (XDR)',
'Security Orchestration',
'Authentication Protocols',
'Kerberos',
'LDAP',
'RADIUS',
'TACACS+',
'Security Awareness',
'Compliance Frameworks',
'ISO 27001',
'NIST Cybersecurity Framework',
'PCI-DSS',
'HIPAA Security',
'Governance, Risk & Compliance (GRC)',

  // ============================================
  // ADDITIONAL TOOLS & TECHNOLOGIES
  // ============================================

  'Postman',
  'Swagger',
  'OpenAPI',
  'Makefile',
  'CMake',
  'Gradle',
  'Maven',
  'npm',
  'pip',
  'conda',
  'Poetry',
  'Virtual Environments',
  'Environment Management',
  'pnpm',
  'yarn',
  'Bun',
  'Deno',
  'nvm',
  'pyenv',
  'asdf',
  'Bazel',
  'Buck',
  'Nx Build',
  'Turborepo',
  'Bruno',
  'Insomnia',
  'ngrok',
  'LocalStack',
  'Minio',
  'Temporal',
  'Conductor',
  'n8n',
  'Zapier',
  'Make',

];
/**
 * Extract technical keywords from text using the pattern list
 * @param {string} text - Text to extract keywords from
 * @returns {Array<string>} - Array of found keywords
 */
function extractTechnicalKeywords(text) {
    if (!text) return [];

    const textLower = text.toLowerCase();
    const foundKeywords = [];

    for (const pattern of TECHNICAL_PATTERNS) {
        const regex = new RegExp(`\\b${pattern}\\b`, 'gi');
        if (regex.test(textLower)) {
            // Normalize the keyword (remove regex escapes)
            const normalized = pattern.replace(/\\b|\\+|\\/g, '').replace(/\s+/g, ' ');
            if (!foundKeywords.includes(normalized)) {
                foundKeywords.push(normalized);
            }
        }
    }

    return foundKeywords.sort();
}

/**
 * Find common keywords between two sets
 * @param {Array<string>} set1 - First keyword set
 * @param {Array<string>} set2 - Second keyword set
 * @returns {Array<string>} - Common keywords
 */
function findCommonKeywords(set1, set2) {
    const set1Lower = new Set(set1.map(k => k.toLowerCase()));
    return set2.filter(k => set1Lower.has(k.toLowerCase()));
}

/**
 * Find missing keywords (in set2 but not in set1)
 * @param {Array<string>} set1 - First keyword set (e.g., resume)
 * @param {Array<string>} set2 - Second keyword set (e.g., JD)
 * @returns {Array<string>} - Missing keywords
 */
function findMissingKeywords(set1, set2) {
    const set1Lower = new Set(set1.map(k => k.toLowerCase()));
    return set2.filter(k => !set1Lower.has(k.toLowerCase()));
}

module.exports = {
    TECHNICAL_PATTERNS,
    extractTechnicalKeywords,
    findCommonKeywords,
    findMissingKeywords
};
